resources:
- name: app
  type: git
  source:
    uri: https://github.com/mellamopablo-personal-tests/concourse-express-test
    branch: master

jobs:
- name: build
  plan:
  - get: app
    trigger: true
  - task: dependencies
    file: app/ci/1-dependencies.yml
  - task: build
    file: app/ci/2-build.yml
  - task: test
    file: app/ci/3-test.yml
