resources:
- name: app
  type: git
  source:
    uri: https://github.com/mellamopablo-personal-tests/concourse-express-test
    branch: master

jobs:
- name: dependencies
  plan:
  - get: app
    trigger: true
  - task: dependencies
    file: app/ci/dependencies.yml
  - task: build
    file: app/ci/build.yml
